version: "3.5"
services:

  jenkins:
    build: .
    container_name: jenkins
    hostname: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 5000:5000
    networks:
    - demo_overlay_net

networks:
  demo_overlay_net:


